### ISSUE TITLE
Open definition navigates to definition and opens "Peek definition" inline

### ISSUE THREAD

**Issue by DBosley** [mrmlnc/vscode-less#36]
When using f12 to navigate to a mixin definition, the file that defines it is opened, and that same file is opened as a 'peek definition' inline.

![image](https://cloud.githubusercontent.com/assets/2766936/23580437/3bb9d3c0-00bf-11e7-9b8d-928e1c911d25.png)

When I press f12:
![image](https://cloud.githubusercontent.com/assets/2766936/23580445/6ac05482-00bf-11e7-99de-a4b658e4601e.png)

Notice the open file is the same one as the peek view.

Note: Right click context menu has the same problem.

**Comment by mrmlnc** [comment]
Should be fixed in `0.6.2` version.
