### ISSUE TITLE
Alt-F12 "Peek Definition" does not work

### ISSUE THREAD

**Issue by DBosley** [mrmlnc/vscode-less#37]
Pressing Alt-F12 doesn't seem to do anything, but pressing F12 opens mixin definitions correctly but also peeks at the same time.
(see #36)

Right-click context menu opens the 'peek defintion' view to the line you right clicked, not the file where the mixin is defined.

**Comment by mrmlnc** [comment]
Should be fixed in 0.6.2 version.
