### ISSUE TITLE
Guard logical operator "when not" expecting bracket "{"

### ISSUE THREAD

**Issue by sjee** [mrmlnc/vscode-less#43]
When using "**not**" when negating the logical operator "**when**", the code gets highlighted with red squigly lines.

Example:

```
.center (@width, @height) when not (@width = "") and not (@height = "") { 
    /* css properties here... */ 
}
```
Underlined with red squigly lines:

- the first angle bracket is underlined _(before @width)_
- all colons of the CSS properties, except for the first property
- the last closing bracket
- detachet ruleset inside the selector (but not when it is the first line after the opening "{" bracket.

<img width="565" alt="screen shot 2018-03-19 at 14 41 04" src="https://user-images.githubusercontent.com/768002/37598846-a465c79a-2b83-11e8-85ec-0ee08ca13f56.png">

When removing "not" the red lines disappear.

**Comment by mrmlnc** [comment]
This extension does not validate files (only provides intellisense). Please file your issue to VS Code repository.
