### ISSUE TITLE
Reference to variable doesn't show up 

### ISSUE THREAD

**Issue by mirkea** [mrmlnc/vscode-less#46]
in a less file with various variables, if I type `@` I get a dropdown with the variable names
https://dl.dropboxusercontent.com/s/4irlx7652e331k3/shot_180603_004815.png

but if I type `color: @`  I get nothing
https://dl.dropboxusercontent.com/s/8iuzs5re0blu1aj/shot_180603_004933.png

**Comment by mrmlnc** [comment]
This is a correct behaviour, because you trying use variable inside `global` context. This is invalid CSS code. The following example should work correctly:

```
.test {
  color: @|
}
```
