### ISSUE TITLE
SASS version. Please.

### ISSUE THREAD

**Issue by mattez** [mrmlnc/vscode-less#47]
When I migrated to **Bootstrap 4**, I have to also migrate **from LESS to SASS**.
I'm really missing some plug-in like this for SASS.
Most favorite VSCODE plugin for SASS do not support autocomplete/inteliSense variables from different .sass files.

Any ideas? Thank you.

**Comment by ayyash** [comment]
There are two extensions for sass:
- https://marketplace.visualstudio.com/items?itemName=aaronphy.scss-scan
- https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss
